# This is a basic workflow to help you get started with Actions

name: API prod environment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Uses the NodeJS actions
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          npm install

      - name: Build NestJS application
        run: npm run build

      # Install dependencies
      - name: Stop API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: root
          key: ${{secrets.DEPLOY_KEY_PROD}}
          port: 22
          script_stop: false
          script: |
            pm2 stop api

      # Deploy to VM
      - name: VM SYNC
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_PROD }}
        with:
          src: /
          options: "--exclude /.git/ --exclude /.github/ --exclude /node_modules/"
          dest: root@${{ secrets.HOST_PROD }}:/root/rool-api/

      # Install dependencies
      - name: Install VM dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: root
          key: ${{secrets.DEPLOY_KEY_PROD}}
          port: 22
          script_stop: false
          script: |
            cd /root/rool-api/
            yarn --ignore-engines

      # Setup config and restart pm2 process
      - name: Config and restart API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: root
          key: ${{ secrets.DEPLOY_KEY_PROD }}
          port: 22
          script_stop: true
          script: |
            cd /root/rool-api/
            rm -rf .env
            echo "NODE_ENV=${{ secrets.NODE_ENV_PROD }}" >> .env
            echo "PORT=${{ secrets.PORT_PROD }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST_PROD }}" >> .env
            echo "DB_USER=${{ secrets.DB_USERNAME_PROD }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD_PROD }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE_PROD }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT_PROD }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET_PROD }}" >> .env
            echo "JWT_EXPIRE=${{ secrets.JWT_EXPIRE_PROD }}" >> .env
            echo "RECOVER_SERVICE_USER_ID=${{ secrets.RECOVER_SERVICE_USER_ID }}" >> .env
            echo "RECOVER_SERVICE_TEMPLATE_ID=${{ secrets.RECOVER_SERVICE_TEMPLATE_ID }}" >> .env
            echo "RECOVER_SERVICE_SERVICE_ID=${{ secrets.RECOVER_SERVICE_SERVICE_ID }}" >> .env
            echo "RE_SECRET=${{ secrets.RE_SECRET_PROD }}" >> .env
            pm2 restart api
